name: fitness
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  dependencies:
  flutter_bloc: ^7.0.1
  firebase_core_platform_interface: 4.5.1
  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1
  firebase_storage: ^10.0.1
  dots_indicator: ^2.0.0
  percent_indicator: ^3.0.1
  url_launcher: ^6.0.9
  sliding_up_panel: ^2.0.0+1
  video_player: ^2.1.12
  custom_timer: ^0.0.6
  image_picker: ^0.8.2
  flutter_local_notifications: ^9.0.0
  flutter_native_timezone: ^2.0.0 
  permission_handler: ^8.1.4+2
  timezone: any
  chewie: 
  # git:
  #     url: 

  


dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true

  
  assets:
    - assets/images/onboarding/
    - assets/images/auth/
    - assets/images/home/
    - assets/images/exercises/
    - assets/icons/home/
    - assets/icons/workouts/
    - assets/icons/social_networks/
    - assets/videos/workouts/

 
  fonts:
    - family: Brand-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Semi-Bold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
       
  
